blank_issues_enabled: yes

contact_links:
  - name: Documentation Forums Category
    url: https://forums.swift.org/c/92
    about: Ask and answer questions about writing documentation
  - name: Swift-DocC Forums Category
    url: https://forums.swift.org/c/80
    about: Ask and answer questions about using Swift-DocC
  - name: Swift-DocC Documentation
    url: https://www.swift.org/documentation/docc/
    about: Learn about how to use Swift-DocC for authoring documentation
